config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: "This movie is already in the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class='container mt-2'>
  <%== simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.order(:title) %>
    <%= f.button :submit, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='container mt-2'>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://startuppakistan.com.pk/wp-content/uploads/2022/08/BB-1-scaled.jpg)">
    CineList
  </div>
  <div class='d-flex justify-content-between'>
    <h2>My Lists</h2>
    <%= link_to 'Create a new movie list', new_list_path, class: 'btn btn-primary text-white' %>
  </div>
  <div class="list-cards mt-2">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? (cl_image_path(list.photo.key)) : (image_path('https://startuppakistan.com.pk/wp-content/uploads/2022/08/BB-1-scaled.jpg')) %>)">
        <%= link_to list.name, list_path(list), class: 'text-decoration-none text-white text-center' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class='container mt-2'>
  <%== simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class='container mt-2'>
  <div class="card-category list-container" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? (cl_image_path(@list.photo.key)) : (image_path('https://startuppakistan.com.pk/wp-content/uploads/2022/08/BB-1-scaled.jpg')) %>)">
    <%= @list.name %>
    <%= link_to 'Add a new bookmark', new_list_bookmark_path(@list), class: 'btn btn-primary text-white bookmark-add-button' %>
  </div>
  <div class="bookmark-cards mt-2 mb-2">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-category bookmark-container" style="background-image: url(<%= bookmark.movie.poster_url %>), linear-gradient(rgba(0,0,0,1), rgba(0,0,0,1))">
        <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this bookmark?' }, class: 'text-white' do %>
          <i class="fa-solid fa-xmark bookmark-delete-icon"></i>
        <% end %>
        <!-- <p class='m-2'><i class="fa-solid fa-quote-left"></i><%= bookmark.comment %><i class="fa-solid fa-quote-right"></i></p> -->
      </div>
    <% end %>
  </div>
  <div>
    <%= link_to 'Back to Lists', lists_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>